name = "lego-piezas-faltantes"
main = ".open-next/worker.js"
compatibility_date = "2026-02-26"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "development"
REBRICKABLE_API_KEY=baff40198c224169b3c860f9fe2292ad
REBRICKABLE_PREWARM_TOKEN=w8FvP9m2Qk7Zx1Tn4Lr6Yp3Hs0Da5Bc8
