name = "lego-piezas-faltantes"
main = ".open-next/worker.js"
compatibility_date = "2026-02-26"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "production"
